# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TimeManagerApp' do
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  pod 'AppCenter/Push', '~> 1.14.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TimeManagerApp

  

  platform :ios, '9.0'
  target 'TimeManagerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TimeManagerApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TimeManagerApp-tvOS

  target 'TimeManagerApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
